@startuml CPUusage
scale 5 as 5 pixels
robust "proc1" as W0
robust "proc2" as W1

@0
W0 is DORMANT
W1 is DORMANT

@1
W0 is WAITING
W1 is WAITING

@500
W0 is READY

@501
W0 is RUNNING

@500
W1 is READY

@600
W1 is RUNNING
W0 is WAITING

@700
W1 is WAITING

@1000
W0 is READY

@1001
W0 is RUNNING

@1000
W1 is READY

@1020
W1 is RUNNING
W0 is WAITING

@1120
W1 is WAITING

@1500
W0 is READY

@1501
W0 is RUNNING

@1500
W1 is READY

@1600
W1 is RUNNING
W0 is WAITING

@1700
W1 is WAITING

@2000
W0 is READY

@2001
W0 is RUNNING

@2000
W1 is READY

@2020
W1 is RUNNING
W0 is WAITING

@2120
W1 is WAITING

@2500
W0 is READY

@2501
W0 is RUNNING

@2500
W1 is READY

@2600
W1 is RUNNING
W0 is WAITING

@2700
W1 is WAITING

@3000
W0 is READY

@3001
W0 is RUNNING

@3000
W1 is READY

@3020
W1 is RUNNING
W0 is WAITING

@3120
W1 is WAITING

@3500
W0 is READY

@3501
W0 is RUNNING

@3500
W1 is READY

@3600
W1 is RUNNING
W0 is WAITING

@3700
W1 is WAITING

@4000
W0 is READY

@4001
W0 is RUNNING

@4000
W1 is READY

@4020
W1 is RUNNING
W0 is WAITING

@4120
W1 is WAITING

@4500
W0 is READY

@4501
W0 is RUNNING

@4500
W1 is READY

@4600
W1 is RUNNING
W0 is WAITING

@4700
W1 is WAITING
@enduml
