@startuml CPUusage
scale 5 as 5 pixels
robust "proc1" as W0
robust "proc2" as W1
robust "proc3" as W2

@0
W0 is DORMANT
W1 is DORMANT
W2 is DORMANT

@1
W2 is WAITING

@200
W2 is READY

@201
W2 is RUNNING

@250
W2 is WAITING

@400
W2 is READY

@401
W2 is RUNNING

@1
W0 is WAITING
W1 is WAITING

@500
W0 is READY

@501
W0 is RUNNING

@405
W2 is WAITING

@500
W1 is READY

@600
W1 is RUNNING
W2 is READY

@700
W2 is RUNNING

@705
W2 is WAITING

@800
W2 is READY

@801
W2 is RUNNING

@600
W0 is WAITING

@700
W1 is WAITING

@850
W2 is WAITING

@1000
W0 is READY

@1001
W0 is RUNNING

@1000
W1 is READY

@1020
W1 is RUNNING

@1000
W2 is READY

@1120
W2 is RUNNING

@1125
W2 is WAITING

@1200
W2 is READY

@1201
W2 is RUNNING

@1205
W2 is WAITING

@1400
W2 is READY

@1401
W2 is RUNNING

@1020
W0 is WAITING

@1120
W1 is WAITING

@1500
W0 is READY

@1501
W0 is RUNNING

@1450
W2 is WAITING

@1500
W1 is READY

@1600
W1 is RUNNING
W2 is READY

@1700
W2 is RUNNING

@1705
W2 is WAITING

@1800
W2 is READY

@1801
W2 is RUNNING

@1600
W0 is WAITING

@1700
W1 is WAITING

@1805
W2 is WAITING

@2000
W0 is READY

@2001
W0 is RUNNING

@2000
W1 is READY

@2020
W1 is RUNNING

@2000
W2 is READY

@2120
W2 is RUNNING

@2170
W2 is WAITING

@2200
W2 is READY

@2201
W2 is RUNNING

@2205
W2 is WAITING

@2400
W2 is READY

@2401
W2 is RUNNING

@2020
W0 is WAITING

@2120
W1 is WAITING

@2500
W0 is READY

@2501
W0 is RUNNING

@2405
W2 is WAITING

@2500
W1 is READY

@2600
W1 is RUNNING
W2 is READY

@2700
W2 is RUNNING

@2750
W2 is WAITING

@2800
W2 is READY

@2801
W2 is RUNNING

@2600
W0 is WAITING

@2700
W1 is WAITING

@2805
W2 is WAITING

@3000
W0 is READY

@3001
W0 is RUNNING

@3000
W1 is READY

@3020
W1 is RUNNING

@3000
W2 is READY

@3120
W2 is RUNNING

@3125
W2 is WAITING

@3200
W2 is READY

@3201
W2 is RUNNING

@3250
W2 is WAITING

@3400
W2 is READY

@3401
W2 is RUNNING

@3020
W0 is WAITING

@3120
W1 is WAITING

@3500
W0 is READY

@3501
W0 is RUNNING

@3405
W2 is WAITING

@3500
W1 is READY

@3600
W1 is RUNNING
W2 is READY

@3700
W2 is RUNNING

@3705
W2 is WAITING

@3800
W2 is READY

@3801
W2 is RUNNING

@3600
W0 is WAITING

@3700
W1 is WAITING

@3850
W2 is WAITING

@4000
W0 is READY

@4001
W0 is RUNNING

@4000
W1 is READY

@4020
W1 is RUNNING

@4000
W2 is READY

@4120
W2 is RUNNING

@4125
W2 is WAITING

@4200
W2 is READY

@4201
W2 is RUNNING

@4205
W2 is WAITING

@4400
W2 is READY

@4401
W2 is RUNNING

@4020
W0 is WAITING

@4120
W1 is WAITING

@4500
W0 is READY

@4501
W0 is RUNNING

@4450
W2 is WAITING

@4500
W1 is READY

@4600
W1 is RUNNING
W2 is READY

@4700
W2 is RUNNING

@4705
W2 is WAITING

@4800
W2 is READY

@4801
W2 is RUNNING

@4600
W0 is WAITING

@4700
W1 is WAITING

@4805
W2 is WAITING

@5000
W0 is READY

@5001
W0 is RUNNING

@5000
W1 is READY

@5020
W1 is RUNNING

@5000
W2 is READY

@5120
W2 is RUNNING

@5170
W2 is WAITING

@5200
W2 is READY

@5201
W2 is RUNNING

@5205
W2 is WAITING

@5400
W2 is READY

@5401
W2 is RUNNING

@5020
W0 is WAITING

@5120
W1 is WAITING

@5500
W0 is READY

@5501
W0 is RUNNING

@5405
W2 is WAITING

@5500
W1 is READY

@5600
W1 is RUNNING
W2 is READY

@5700
W2 is RUNNING

@5750
W2 is WAITING

@5800
W2 is READY

@5801
W2 is RUNNING

@5600
W0 is WAITING

@5700
W1 is WAITING

@5805
W2 is WAITING

@enduml
